version: "3.8"

services:
  idp-db:
    image: postgres:15.2
    container_name: idp-db
    hostname: idp-db.local
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Passw-0rd
    ports:
      - 30426:5432
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    networks:
      keycloak-idp-network:

  idp:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    container_name: idp
    hostname: idp.local
    ports:
      - "30424:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Passw-0rd
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: Passw-0rd
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://idp-db.local:5432/keycloak
      # Uncomment the line below if you want to specify JDBC parameters.
      # The parameter below is just an example, and it shouldn't be used in production without knowledge.
      # It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    depends_on:
      - idp-db
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    networks:
      keycloak-idp-network:

  keycloak-dev:
    image: keycloak-dev:0.1
    container_name: keycloak-dev
    hostname: keycloak-dev.local
    working_dir: /work
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/work:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    networks:
      keycloak-idp-network:

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - "30423:3000"
    depends_on:
      - idp

networks:
  keycloak-idp-network:

volumes:
  postgres-data:
    driver: local
